language: node_js
node_js:
   - "8"

cache:
  directories:
    - "node_modules"

jobs:
  include:
    - stage: Test
      name: Unit tests
      script: npm test
      name: E2E tests
      script: npm run test:e2e
