language: node_js
node_js:
   - "8"

cache:
  directories:
    - "node_modules"

jobs:
  include:
    - stage: build
      script: npm run build

    - stage: unit tests
      script: npm test

    - stage: e2e tests
      script: npm run test:e2e
